# 此工作流程用于将项目部署到 GitHub Pages。
# 当 `main` 分支有新的推送时，或者手动从 GitHub Actions 选项卡触发时，工作流程将自动运行。

name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # 仅在 `main` 分支有推送时触发
    paths:
      - 'docs/**'
      - 'packages/**'
      - '.github/workflows/deploy.yml'
      - 'pnpm-lock.yaml'

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境运行任务

    steps:
      # 检出代码到工作目录
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 pnpm 包管理器，并指定版本为 9
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 设置 Node.js 环境，并指定版本为 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 获取 pnpm store 目录路径，用于缓存
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # 设置 pnpm 缓存
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 安装项目依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 运行代码检查
      - name: Lint code
        run: pnpm run lint

      # 运行测试（如果有）
      - name: Run tests
        run: pnpm run test || echo "No tests found"

      # 构建 UI 组件库
      - name: Build UI library
        run: pnpm run ui:build

      # 使用 VitePress 构建文档
      - name: Build documentation
        run: pnpm run docs:build

      # 配置 GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      # 将构建后的文档部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
